// Unique "About This Service" content for individual service detail pages
// Replaces the generic duplicate paragraph that was hurting SEO

export const SERVICE_ABOUT: Record<string, string> = {
  // PLUMBING
  "water-heater-installation": "Water heater installation in the UAE involves more than just connecting pipes — unit sizing matters based on your household size, bathroom count, and whether you need a storage tank (50-80 liters for apartments, 80-120 liters for villas) or an instant tankless heater. Our plumbers supply units from Ariston, Midea, and other UAE-stocked brands, handle wall mounting with proper bracket load support, connect hot and cold water lines, install the pressure relief valve, and test for leaks before handover. We also remove and dispose of your old unit. Most apartment installations are completed in 2-3 hours. Villa installations with longer pipe runs may take half a day.",
  "water-heater-repair": "Common water heater problems in UAE homes include no hot water (usually a failed heating element or tripped thermostat), water not getting hot enough (sediment buildup or thermostat miscalibration), and tank leaks (corroded anode rod or tank bottom). Our technicians diagnose the issue on-site, carry replacement elements, thermostats, and anode rods for popular brands, and complete most repairs in a single visit. If the tank itself is corroded beyond repair, we provide a same-day replacement quote with installation included.",
  "leak-repair": "Water leaks in UAE apartments and villas range from visible drips under sinks to hidden pipe leaks inside walls that show up as damp patches or peeling paint. Our plumbers use pressure testing and moisture detection to pinpoint the exact leak location before cutting into walls or floors, minimizing damage and repair costs. Common fixes include pipe joint resealing, washer replacement, flexi-hose swap, and corroded pipe section replacement. Emergency leak calls in Dubai and Sharjah are prioritized for same-day response.",
  "drain-cleaning": "Blocked drains in UAE kitchens are usually caused by grease and food particle buildup, while bathroom drains clog from hair and soap residue. Our plumbers use mechanical drain snakes for standard blockages and hydro-jetting for severe or deep-line clogs that chemical cleaners can't reach. We also inspect drain condition and recommend preventive measures — like grease traps for kitchen sinks — to reduce repeat blockages. Floor drain cleaning in bathrooms and laundry rooms is included in our standard service.",
  "pipe-repair": "Pipe repairs in UAE buildings range from simple fixes like replacing a burst flexi-hose under a sink (20 minutes) to more involved work like cutting out and replacing a corroded galvanized pipe section with modern PPR or CPVC pipe (2-4 hours). Our plumbers carry fittings for all common pipe types found in UAE buildings — galvanized steel in older buildings, copper in mid-age construction, and PPR/CPVC in newer builds. We pressure-test after every repair to confirm the fix holds.",
  "faucet-repair": "A dripping faucet wastes up to 20 liters of water per day in the UAE. Most faucet repairs involve replacing the internal cartridge (for mixer taps) or rubber washer (for traditional taps). Our plumbers carry cartridges for popular brands like Grohe, Hansgrohe, andDERA. If the faucet body is corroded or cracked, we provide a replacement quote with same-visit installation. Repair typically takes 15-30 minutes per faucet.",
  "toilet-repair": "Toilet issues in UAE homes include continuous running water (usually a faulty fill valve or flapper), weak flush (blocked rim jets or low tank water level), and base leaks (failed wax ring seal). Our plumbers diagnose and fix most toilet problems in 30-60 minutes, carrying standard replacement parts on every service van. For older toilets with discontinued parts, we recommend full mechanism replacement rather than repeated patchwork repairs.",
  "sink-installation": "Kitchen and bathroom sink installation includes removing the old unit (if replacing), preparing the countertop cutout, mounting the sink (under-mount, top-mount, or vessel style), connecting the drain assembly with P-trap, installing the faucet, and testing for leaks. Our plumbers work with all counter materials — granite, marble, engineered stone, and laminate. Most sink installations are completed in 2-3 hours including cleanup.",
  "shower-installation": "Shower installation covers fitting the shower head and arm, installing the mixer valve (concealed or exposed), connecting hot and cold supply lines, setting up the floor drain, and sealing all joints. For shower enclosure upgrades, we coordinate glass panel installation and floor waterproofing. Our plumbers handle both simple showerhead swaps (30 minutes) and full shower system installations (half day).",
  // AC
  "ac-cleaning": "AC cleaning in the UAE is essential every 3-4 months given the extreme dust and humidity. Our service includes opening the indoor unit, removing and washing the filters, cleaning the evaporator coil with approved foam cleaner, flushing the condensate drain line to prevent water leaks, cleaning the blower wheel, and sanitizing the unit with anti-bacterial spray. For the outdoor condenser, we rinse the coil fins with pressurized water to remove sand and debris that reduce cooling efficiency. Each unit service takes 30-45 minutes.",
  "ac-gas-refill": "If your AC is running but not cooling properly, low refrigerant gas is often the cause. Our technicians connect gauges to measure your system's pressure, identify any gas leaks (which must be fixed before refilling), and top up with the correct refrigerant type — R410A for newer units or R22 for older systems. We also check the compressor amperage to confirm the system is operating within rated parameters after the refill. A standard gas refill takes 30-60 minutes per unit.",
  "ac-not-cooling-repair": "When your AC runs but blows warm or room-temperature air, the cause could be low gas, a dirty evaporator coil blocking airflow, a faulty compressor capacitor, a stuck expansion valve, or a malfunctioning thermostat sensor. Our technicians systematically check each component to identify the actual fault rather than guessing. Common fixes include capacitor replacement, coil cleaning, gas refill, and thermostat recalibration — most completed in a single visit.",
  "ac-water-leak-repair": "Water dripping from your indoor AC unit is almost always caused by a clogged condensate drain line — dust, algae, and mineral deposits block the pipe over time, causing water to back up into the drain pan and overflow. Our fix involves clearing the drain using compressed air or a wet vacuum, flushing the line with cleaning solution, and checking the drain pan for cracks. In some cases, the drain pan itself needs replacement. This is a 30-45 minute repair.",
  "ac-annual-maintenance": "Our annual AC maintenance plan includes 4 quarterly servicing visits covering filter wash, coil cleaning, gas pressure check, drain flush, and performance testing on every unit in your property. Between visits, you get priority scheduling for any AC issues, with emergency calls responded to within 4 hours. The plan pays for itself by preventing breakdowns, extending unit lifespan, and maintaining cooling efficiency that reduces electricity bills by 10-20%.",
  "ac-filter-cleaning": "AC filters should be cleaned monthly during UAE summers when AC runs 16-20 hours daily. Clogged filters reduce airflow by up to 50%, forcing the compressor to work harder and increasing electricity consumption. Our technicians remove each filter, wash with mild detergent, dry thoroughly, and reinstall — checking filter condition and recommending replacement for filters that are torn or permanently discolored. Takes 10-15 minutes per unit.",
  "split-ac-installation": "Split AC installation includes mounting the indoor unit bracket on the wall, drilling the pipe hole through the exterior wall, routing copper pipes and electrical cable to the outdoor unit location, mounting the outdoor condenser unit on a bracket or ground pad, connecting refrigerant lines, pressure testing for leaks, vacuuming the system, charging with refrigerant gas, and testing cooling performance. Standard installation in a pre-piped room takes 2-3 hours; new installations requiring pipe routing take 4-6 hours.",
  "ac-duct-cleaning": "AC duct cleaning removes accumulated dust, mold spores, and debris from your ductwork that circulate through your home every time the AC runs. Our process includes inspection with a duct camera, mechanical brushing of duct interiors, HEPA-filtered vacuum extraction of loosened debris, coil cleaning at the air handling unit, and anti-microbial treatment of duct surfaces. A standard 2-bedroom apartment duct cleaning takes 3-4 hours; villas with more extensive ductwork take 5-8 hours.",
  // CLEANING
  "deep-home-cleaning": "Deep home cleaning goes far beyond regular surface cleaning — we target the areas that accumulate grime over weeks and months but get missed in routine cleaning. This includes inside kitchen cabinets and behind appliances, bathroom tile grout scrubbing and descaling, window track and frame cleaning, skirting board and door frame dusting, light fixture cleaning, under-furniture vacuuming, and balcony floor scrubbing. A 2-bedroom apartment deep clean takes 4-6 hours with a 2-person team; villas take 6-10 hours depending on size.",
  "move-in-move-out-cleaning": "Move-in and move-out cleaning is designed to meet landlord handover standards in the UAE. We clean every surface a property inspector would check — kitchen cabinets (inside and out), appliance exteriors, bathroom fixtures and tiles, all floors, window glass and frames, wardrobe interiors, balcony and storage areas, and door handles and light switches. Many landlords in Dubai and Sharjah require professional cleaning receipts as part of the deposit return process — we provide these on completion.",
  "sofa-cleaning": "Fabric sofas in UAE homes collect dust faster than in milder climates due to desert sand particles and AC-circulated dust. Our steam cleaning method injects hot water and cleaning solution into the fabric under pressure, then immediately extracts it along with embedded dirt, allergens, and bacteria. The result is a sofa that looks refreshed, smells clean, and dries within 2-4 hours. For leather sofas, we use a separate pH-balanced cleaning and conditioning process that protects the material from cracking.",
  "carpet-cleaning": "UAE carpets take a beating from fine desert sand that works its way deep into fibers, past what regular vacuuming can reach. Our hot-water extraction method forces cleaning solution through the carpet pile and immediately vacuums it out, pulling up embedded sand, dust mites, and stains from the carpet backing. This method is recommended by most carpet manufacturers and significantly extends carpet lifespan compared to dry-powder cleaning. A standard room carpet takes 20-30 minutes to clean and 3-4 hours to fully dry.",
  "mattress-cleaning": "Mattresses accumulate sweat, dead skin cells, and dust mites over time — a typical mattress can harbor millions of dust mites after just two years of use. Our cleaning process includes thorough vacuuming with a HEPA-filter machine, targeted stain treatment for sweat marks and spills, UV-C light sanitization to kill bacteria and mites, and optional anti-allergen spray treatment. Most single and double mattresses take 30-45 minutes to clean and can be slept on the same evening.",
  "villa-cleaning": "Villa cleaning covers significantly more ground than apartment cleaning — multiple bedrooms, 3-5 bathrooms, larger kitchen with more cabinet space, maid's room, storage areas, and sometimes a garage, garden, and pool deck. Our villa teams arrive with 2-3 cleaners and commercial-grade equipment to complete the job efficiently. We customize the cleaning checklist based on your villa's layout and which areas need the most attention, rather than applying a rigid apartment-style package to a completely different property type.",
  "office-cleaning": "Office cleaning requirements differ from home cleaning — desks need wiping without disturbing papers and equipment, communal kitchens need daily sanitization, washrooms need restocking and deep cleaning, and floor cleaning needs to happen during off-hours to avoid disrupting work. We offer early morning (6-8 AM), evening (after 6 PM), and weekend cleaning slots specifically for office clients. Recurring plans include daily, twice-weekly, and weekly options with consistent teams assigned to your office.",
  "apartment-cleaning": "Apartment cleaning covers kitchen (counters, stovetop, sink, cabinet fronts), bathroom (toilet, shower, mirror, floor), bedroom (bed making, surface dusting, floor), living area (furniture dusting, floor mopping), and general tidying. Our cleaners follow a room-by-room checklist to ensure nothing gets missed. Studio and 1-bedroom apartments take 2-3 hours; 2-bedroom units take 3-4 hours. We bring all cleaning supplies and equipment — you don't need to provide anything.",
  "window-cleaning": "Window cleaning in the UAE needs to be done more frequently than in milder climates due to sand and dust deposits that build up quickly, especially after sandstorms. Our service covers interior glass cleaning, exterior glass cleaning (for accessible windows), frame and track cleaning to remove sand buildup, and squeegee finishing for streak-free results. For high-rise exterior windows, we coordinate with building management for rope access or BMU (building maintenance unit) scheduling.",
  "curtain-cleaning": "Curtains in UAE homes act as dust filters, trapping fine sand particles and AC-circulated dust in their fabric folds. Our curtain cleaning process includes careful removal from rods or tracks, fabric type assessment (different methods for sheer, blackout, and lined curtains), professional washing or dry cleaning as appropriate, pressing or steaming to remove wrinkles, and reinstallation on your existing hardware. Turnaround is typically 24-48 hours for standard curtains.",
  "post-construction-cleaning": "Post-construction cleaning removes the fine dust, paint splatter, adhesive residue, and debris left behind after renovation or building work. This requires different equipment and techniques than regular cleaning — HEPA-filter vacuums for concrete dust (which regular vacuums just recirculate), scraper tools for paint and adhesive on glass and tiles, and industrial degreasers for construction grime on fixtures. A standard apartment post-construction clean takes 6-8 hours; villas take 1-2 full days.",
  "water-tank-cleaning": "Water tank cleaning is recommended every 6 months in the UAE to prevent sediment buildup, algae growth, and bacterial contamination. Our process includes draining the tank completely, scrubbing interior walls and floor to remove sediment and biofilm, disinfecting with chlorine solution at the correct concentration, rinsing thoroughly, and refilling. We provide a cleaning certificate that many Dubai and Sharjah municipalities require for residential and commercial properties.",
  // ELECTRICAL
  "light-installation": "Light installation covers ceiling-mounted fixtures, wall sconces, recessed downlights, spotlights, and outdoor lights. Our electricians handle the full process — turning off the circuit, removing old fixtures, checking wire condition, connecting the new light (live, neutral, earth), securing the mounting, and testing. For new installation points where no wiring exists, we route cable from the nearest junction box or DB panel. Standard light fitting takes 20-30 minutes; new wiring points take 1-2 hours.",
  "db-box-work": "Distribution board (DB box) work includes upgrading old fuse boxes to modern MCB/RCCB panels, adding new circuit breakers for additional loads, labeling circuits for easy identification, installing earth leakage protection devices, and balancing loads across phases. Many older UAE buildings still have outdated DB boxes that trip frequently or lack proper earth leakage protection — upgrading is both a safety improvement and a convenience fix. Standard DB upgrade takes 3-5 hours.",
  "chandelier-installation": "Chandelier installation requires a ceiling anchor rated for the fixture weight (some chandeliers exceed 30kg), proper electrical connection with a junction box, and careful assembly of the chandelier components. For heavy fixtures, we install a ceiling plate with expansion bolts into concrete. Our electricians also set up dimmer switches if requested and test all lamp positions. Standard chandelier installation takes 1-3 hours depending on complexity.",
  // HANDYMAN
  "furniture-assembly": "Flat-pack furniture assembly covers wardrobes, desks, bed frames, bookshelves, TV units, and dining tables from IKEA, Home Centre, Pan Emirates, and other UAE retailers. Our handymen follow manufacturer instructions precisely, use proper tools (not just the included Allen key), and ensure all fixings are tight and the piece is level and stable. A standard wardrobe takes 1.5-2.5 hours; a bed frame 1-1.5 hours; a desk 45-60 minutes.",
  "tv-mounting": "TV wall mounting includes selecting the right bracket type for your TV size and wall material (concrete, drywall, or block), drilling with appropriate anchors, mounting the bracket, hanging the TV, connecting cables, and concealing wires in a cable management channel or behind-wall conduit if requested. We bring brackets in common sizes or install customer-supplied brackets. Standard TV mounting takes 45-90 minutes.",
  "interior-painting": "Interior painting in UAE apartments and villas includes wall preparation (filling holes, sanding rough spots, cleaning surfaces), masking tape protection for door frames, windows, and switches, primer coat where needed, and two finish coats of emulsion paint. We use Jotun, National Paints, or customer-specified brands. A standard bedroom takes 1 day; a full 2-bedroom apartment takes 3-4 days. All furniture is covered and floors protected during work.",
  // PEST CONTROL
  "general-pest-treatment": "General pest treatment covers the most common household pests in the UAE — cockroaches, ants, silverfish, and spiders. Our treatment includes spraying residual insecticide along baseboards, under sinks, behind appliances, and around entry points, plus applying gel bait in kitchen cabinets and bathroom fixtures where cockroaches harbor. One treatment typically provides 2-3 months of protection. We use municipality-approved, low-toxicity products safe for homes with children and pets.",
  "cockroach-control": "Cockroach control in UAE homes uses a combination of gel bait (placed in cabinet hinges, behind appliances, and near pipe entry points) and residual spray (along baseboards and under sinks). Gel bait is particularly effective because cockroaches eat it and carry it back to the nest, killing colony members that never directly contact the treated area. Our treatment provides 2-3 months of control. For severe infestations, we recommend a follow-up visit after 2 weeks.",
  "bed-bug-treatment": "Bed bug treatment requires a different approach than general pest control — bed bugs are resistant to many standard insecticides and hide in mattress seams, bed frame joints, and headboard crevices. Our treatment combines targeted spray application with heat treatment of the mattress and bed frame, plus treatment of adjacent furniture and baseboards. We recommend a follow-up inspection 2 weeks after treatment to confirm all life stages (including eggs) have been eliminated.",
  "termite-control": "Termite control in the UAE targets subterranean termites that enter buildings from soil contact points — common in villas with ground-floor wooden fixtures, door frames, and furniture. Our treatment options include soil barrier treatment (injecting termiticide into the soil around the building perimeter), bait station installation (monitoring stations that detect and eliminate colonies), and spot treatment for active infestations in specific wooden elements. Treatment choice depends on property type and infestation severity.",
  // MOVERS
  "apartment-moving": "Apartment moving includes furniture disassembly (beds, wardrobes, dining tables), protective wrapping of all items (bubble wrap for fragile items, blankets for furniture), loading onto our vehicles with proper securing, transport to the new location, unloading, and furniture reassembly. We provide all packing materials. A studio move typically takes 3-4 hours and uses a small truck; a 2-bedroom apartment takes 5-7 hours and uses a larger vehicle. We handle moves within Dubai, between emirates, and across the UAE.",
  "villa-moving": "Villa moving is a larger-scale operation covering multiple rooms, outdoor furniture, garden items, and sometimes a garage full of stored items. We deploy 4-6 movers with a large truck (or two trucks for larger villas), with a dedicated supervisor coordinating the packing sequence, loading order, and reassembly at the destination. Heavy items like safes, pianos, and gym equipment require additional handling equipment. A standard 3-bedroom villa move takes a full day.",
  // GARDEN
  "pool-cleaning": "Pool cleaning includes skimming the surface for leaves and debris, vacuuming the pool floor, brushing walls and tile lines, cleaning the skimmer basket and pump strainer, testing and balancing water chemistry (pH, chlorine, alkalinity), and inspecting the pump and filter for proper operation. Regular cleaning prevents algae growth, keeps water safe for swimming, and extends equipment lifespan. Our standard visit takes 45-60 minutes for residential pools.",
  "pool-maintenance": "Monthly pool maintenance goes beyond basic cleaning — it includes filter backwashing or cartridge cleaning, pump performance check, salt chlorinator cell inspection (if applicable), equipment lubrication, tile calcium deposit removal, and seasonal adjustments to chemical dosing as water temperature changes. We provide a written condition report after each visit so you can track your pool system's health over time.",
  // BUILDING MAINTENANCE
  "property-snagging": "Property snagging is a systematic inspection of a newly built or renovated property to identify defects before you accept handover from the developer. Our inspectors check 200+ points including paint finish quality, tile alignment and grouting, plumbing fixtures and water pressure, electrical outlets and switches, AC cooling performance and drainage, door and window operation, kitchen cabinet alignment, and balcony drainage. You receive a detailed report with photos within 24 hours, which you submit to the developer for rectification.",
  "residential-amc": "Our residential AMC bundles the maintenance services a typical UAE home needs throughout the year into one predictable annual contract. Standard coverage includes quarterly AC servicing for all units, bi-annual plumbing inspection, annual electrical safety check, quarterly pest control treatment, and a set number of emergency callouts per month. The plan eliminates the hassle of booking individual services and typically costs 20-30% less than paying for the same services separately.",
};

export function getServiceAbout(slug: string): string {
  return SERVICE_ABOUT[slug] || "";
}
