// Unique one-line descriptions for each service — eliminates duplicate content on subcategory listing pages
// Key = service slug, Value = unique 10-15 word description

export const SERVICE_DESCRIPTIONS: Record<string, string> = {
  // Cleaning > Deep Cleaning
  "deep-home-cleaning": "Full home scrub covering kitchens, bathrooms, bedrooms, and hidden dust spots.",
  "move-in-move-out-cleaning": "Handover-ready clean for landlords and tenants — walls, cabinets, and balconies.",
  "post-construction-cleaning": "Remove cement dust, paint splatter, and debris after renovation or building work.",
  "spring-cleaning": "Seasonal refresh targeting curtains, upholstery, windows, and neglected corners.",
  // Cleaning > Regular
  "house-cleaning": "Routine surface cleaning for kitchens, bathrooms, floors, and living areas.",
  "apartment-cleaning": "Quick apartment tidy-up — mopping, dusting, bathroom wipe, and trash removal.",
  "villa-cleaning": "Multi-room villa clean including maid quarters, garage, and outdoor areas.",
  "office-cleaning": "Desk, floor, and washroom sanitation for productive workspaces.",
  "weekly-cleaning": "Scheduled weekly visits keeping your home consistently dust-free.",
  "monthly-cleaning": "Comprehensive monthly deep-surface clean for busy households.",
  // Cleaning > Specialized
  "sofa-cleaning": "Steam extraction that lifts embedded stains, odors, and dust mites from fabric.",
  "carpet-cleaning": "Hot-water extraction removing ground-in dirt and allergens from carpet fibers.",
  "mattress-cleaning": "UV sanitization plus steam clean to remove sweat, dust mites, and bacteria.",
  "curtain-cleaning": "On-site or off-site curtain wash preserving fabric color and pleat shape.",
  "water-tank-cleaning": "Tank draining, sediment removal, and chlorine disinfection for safe water supply.",
  "kitchen-deep-cleaning": "Exhaust hood degreasing, oven scrub, fridge clean, and countertop sanitization.",
  "bathroom-deep-cleaning": "Tile grout scrub, mold treatment, toilet descaling, and fixture polishing.",
  "window-cleaning": "Interior and exterior glass cleaning with streak-free squeegee technique.",
  // Cleaning > Facade
  "facade-cleaning": "Building exterior wash using rope access or boom lift for high-rise surfaces.",
  "pressure-washing": "High-pressure water jet cleaning for driveways, parking areas, and walls.",
  "solar-panel-cleaning": "Dust and grime removal restoring solar panel output by up to 25%.",
  // Cleaning > Sanitization
  "home-disinfection": "EPA-approved disinfectant fogging for living spaces and high-touch surfaces.",
  "office-disinfection": "Workspace-wide antimicrobial spray treatment with minimal downtime.",
  "villa-sanitization": "Room-by-room sanitization covering AC vents, door handles, and bathrooms.",
  // AC
  "ac-cleaning": "Coil wash, filter clean, and drain flush restoring full cooling output.",
  "ac-gas-refill": "Refrigerant pressure test and R410A or R22 gas top-up to rated levels.",
  "ac-filter-cleaning": "Quick filter removal, wash, and reinstall for improved air quality.",
  "ac-annual-maintenance": "Year-round AC care plan with quarterly servicing and priority repairs.",
  "ac-not-cooling-repair": "Diagnosis and fix for warm air output — compressor, fan, or gas issues.",
  "ac-water-leak-repair": "Clogged drain line clearing and drip tray repair to stop indoor leaks.",
  "ac-thermostat-repair": "Sensor calibration or thermostat replacement for accurate temperature control.",
  "ac-compressor-repair": "Compressor diagnosis, capacitor swap, or full unit replacement.",
  "split-ac-installation": "Wall bracket mount, copper piping, drainage setup, and gas charging.",
  "window-ac-installation": "Sleeve fitting, electrical hookup, and sealing for window AC units.",
  "central-ac-service": "Multi-zone ducted system check — AHU, thermostat, and ductwork inspection.",
  "ac-duct-cleaning": "Duct vacuuming, coil treatment, and vent sanitization for cleaner airflow.",
  "kitchen-exhaust-cleaning": "Hood, duct, and fan degreasing meeting municipality fire safety codes.",
  "dryer-vent-cleaning": "Lint buildup removal reducing fire risk and improving dryer efficiency.",
  // Plumbing
  "leak-repair": "Pipe joint sealing, washer replacement, and hidden leak detection.",
  "pipe-repair": "Cracked or burst pipe fix using sleeve clamps or section replacement.",
  "faucet-repair": "Dripping tap fix — cartridge, washer, or valve seat replacement.",
  "drain-cleaning": "Blocked sink or floor drain cleared using snake or hydro-jetting.",
  "toilet-repair": "Flush mechanism fix, fill valve swap, and wax ring sealing.",
  "water-heater-installation": "New tank or tankless heater supply, mount, and plumbing connection.",
  "water-heater-repair": "Thermostat reset, element replacement, and leak repair for water heaters.",
  "sink-installation": "Under-mount or top-mount sink fitting with drain and faucet hookup.",
  "shower-installation": "Shower head, mixer valve, and drain installation or upgrade.",
  "water-pump-installation": "Booster pump supply, mounting, and pressure switch configuration.",
  "water-pump-repair": "Pump motor, impeller, or pressure tank diagnosis and replacement.",
  "water-filter-installation": "Under-sink or whole-house filtration system setup with cartridge.",
  // Electrical
  "power-socket-repair": "Loose or sparking outlet fix — wiring check and socket face replacement.",
  "circuit-breaker-repair": "Tripping breaker diagnosis, MCB swap, and load balancing.",
  "electrical-fault-finding": "Systematic circuit testing to locate short circuits and wiring faults.",
  "db-box-work": "Distribution board upgrade, breaker labeling, and earth leakage fitting.",
  "light-installation": "Ceiling, wall, and recessed light fitting with switch wiring.",
  "chandelier-installation": "Heavy fixture mounting with ceiling anchor, wiring, and dimmer setup.",
  "ceiling-fan-installation": "Fan bracket mount, blade assembly, speed controller, and balancing.",
  "exhaust-fan-installation": "Kitchen or bathroom exhaust fan fitting with duct and exterior vent.",
  "wiring-rewiring": "Partial or full property rewiring using fire-rated cable to UAE code.",
  // Handyman
  "furniture-assembly": "Flat-pack wardrobe, desk, bed frame, and shelving unit assembly.",
  "tv-mounting": "Wall bracket install, cable concealment, and tilt adjustment for TVs.",
  "shelf-installation": "Floating shelf, bracket shelf, and display unit wall mounting.",
  "door-repair": "Hinge adjustment, lock mechanism fix, and door closer installation.",
  "lock-installation": "Deadbolt, smart lock, or cylinder lock fitting and key setup.",
  "curtain-installation": "Curtain rod, track, or motorized rail mounting and fabric hanging.",
  "custom-carpentry": "Built-in shelves, closet modifications, and bespoke wood fixtures.",
  "cabinet-repair": "Hinge replacement, door realignment, and drawer runner fix.",
  "door-replacement": "Old door removal, frame prep, and new door hanging with hardware.",
  "interior-painting": "Wall prep, primer coat, and two-coat finish for rooms and hallways.",
  "exterior-painting": "Facade paint using UV-resistant exterior coating with scaffold setup.",
  "wallpaper-installation": "Surface prep, adhesive application, and precision wallpaper hanging.",
  "touch-up-painting": "Scuff and mark cover-up using color-matched paint on walls and trim.",
  // Renovation
  "kitchen-renovation": "Layout redesign, cabinet install, countertop, backsplash, and plumbing.",
  "bathroom-renovation": "Fixture upgrade, waterproofing, tiling, and vanity installation.",
  "full-apartment-renovation": "Complete interior overhaul — flooring, paint, kitchen, bathrooms, and electrical.",
  "villa-renovation": "Multi-room villa upgrade covering structure, finishes, and MEP systems.",
  "office-fit-out": "Partition walls, ceiling grid, flooring, networking, and AC ducting.",
  "retail-fit-out": "Shopfront, display units, lighting, and POS counter installation.",
  "restaurant-fit-out": "Kitchen hood system, dining layout, washroom, and compliance setup.",
  "gypsum-partition": "Lightweight gypsum board walls for room division and office layout.",
  "ceiling-work": "False ceiling installation — gypsum, grid, or stretch ceiling options.",
  "tiling": "Floor and wall tile laying with leveling, grouting, and edge trim.",
  "flooring": "Vinyl, laminate, porcelain, or marble floor supply and installation.",
  "masonry": "Block wall construction, plastering, and structural patching work.",
  "waterproofing": "Roof, bathroom, and terrace membrane application preventing leaks.",
  "glass-work": "Shower enclosure, glass partition, and mirror installation.",
  "aluminum-work": "Window frame, door frame, and cladding panel fabrication and fitting.",
  // Pest Control
  "cockroach-control": "Gel bait and residual spray targeting kitchen and bathroom harborage.",
  "ant-control": "Trail disruption, bait station placement, and perimeter barrier spray.",
  "spider-control": "Web removal, crack sealing, and residual spray in affected areas.",
  "general-pest-treatment": "Multi-pest spray covering cockroaches, ants, silverfish, and spiders.",
  "bed-bug-treatment": "Heat treatment and residual spray eliminating all bed bug life stages.",
  "termite-control": "Soil barrier, bait system, or spot treatment protecting wooden structures.",
  "rodent-control": "Bait stations, snap traps, and entry point sealing for rats and mice.",
  "mosquito-control": "Larvicide in standing water plus adult mosquito fogging treatment.",
  "bird-control": "Spike strips, netting, and deterrent gel preventing bird roosting.",
  // Appliance Repair
  "washing-machine-repair": "Drum, motor, pump, or control board diagnosis and part replacement.",
  "dryer-repair": "Heating element, belt, or thermostat fix for tumble and condenser dryers.",
  "refrigerator-repair": "Compressor, thermostat, or defrost system repair for all fridge brands.",
  "freezer-repair": "Temperature issue diagnosis — seal replacement, gas check, or compressor.",
  "cooker-repair": "Burner ignition, oven element, and gas valve repair for cooktops.",
  "oven-repair": "Heating element swap, thermostat calibration, and door seal replacement.",
  "dishwasher-repair": "Spray arm, drain pump, or inlet valve fix for dishwasher malfunctions.",
  "microwave-repair": "Magnetron, door switch, or turntable motor diagnosis and replacement.",
  "water-dispenser-repair": "Cooling compressor, heating tank, or tap valve fix for water coolers.",
  "water-heater-repair-appliance": "Element burnout, thermostat fault, or tank leak repair on water heaters.",
  // Movers
  "apartment-moving": "Furniture disassembly, protective wrapping, transport, and reassembly.",
  "villa-moving": "Full villa relocation with packing, loading, transport, and unpacking.",
  "studio-moving": "Budget studio move — loading, transport, and unloading in one trip.",
  "office-moving": "Desk, IT equipment, and filing cabinet relocation with minimal downtime.",
  "warehouse-moving": "Pallet racking disassembly, heavy item transport, and warehouse setup.",
  "professional-packing": "Box supply, bubble wrap, and careful item-by-item packing service.",
  "storage-service": "Short-term and long-term secure storage in climate-controlled facilities.",
  "furniture-moving": "Single-item or multi-piece furniture transport between locations.",
  // Garden
  "lawn-mowing": "Regular grass cutting, edging, and clipping collection for tidy lawns.",
  "garden-cleanup": "Leaf clearing, weed removal, pruning, and garden waste disposal.",
  "hedge-trimming": "Shape trimming and height reduction for hedges and border plants.",
  "tree-trimming": "Branch cutting, crown thinning, and deadwood removal by trained crew.",
  "plant-maintenance": "Watering schedule setup, fertilizing, pest check, and seasonal replanting.",
  "landscape-design": "Garden layout planning, plant selection, and hardscape design for UAE climate.",
  "irrigation-system": "Drip and sprinkler system design, installation, and timer programming.",
  "artificial-grass": "Synthetic turf supply, base prep, and installation for zero-maintenance lawns.",
  "pool-cleaning": "Skimming, vacuuming, chemical balancing, and filter basket cleaning.",
  "pool-maintenance": "Weekly chemical test, filter service, pump check, and tile brushing.",
  "pool-repair": "Pump motor, filter housing, or plumbing leak repair for pool systems.",
  // Building Maintenance
  "villa-maintenance": "Scheduled villa upkeep covering AC, plumbing, electrical, and painting.",
  "apartment-maintenance": "Ongoing apartment care — minor repairs, AC check, and fixture upkeep.",
  "office-maintenance": "Workplace system checks — lighting, AC, plumbing, and electrical safety.",
  "commercial-maintenance": "Building-wide maintenance for retail, warehouse, and commercial properties.",
  "property-snagging": "Defect inspection on new handovers — paint, tile, plumbing, and AC check.",
  "annual-inspection": "Yearly property audit covering structure, MEP systems, and safety compliance.",
  "safety-inspection": "Fire alarm, extinguisher, and electrical safety certification check.",
  "pre-purchase-inspection": "Buyer's property assessment before purchase — condition report provided.",
  "residential-amc": "Annual contract covering quarterly AC, plumbing, electrical, and pest control.",
  "commercial-amc": "Full-building AMC with scheduled maintenance and emergency response.",
  "villa-amc": "Villa-specific annual plan covering all systems plus garden and pool.",
  "high-rise-cleaning": "Rope access or BMU cleaning for building facades and exterior glass.",
  "rope-access-maintenance": "Harness-based exterior work for painting, sealing, and inspection.",
  // Lifestyle
  "maid-service": "Trained housekeepers for daily or weekly home cleaning and tidying.",
  "ironing-service": "Garment pressing and folding — shirts, trousers, dresses, and linens.",
  "laundry-service": "Wash, dry, fold, and deliver for household clothing and bed linens.",
  "event-cleaning": "Pre-event setup clean and post-event deep clean for venues and homes.",
  "event-setup-support": "Chair, table arrangement, decoration setup, and post-event teardown.",
  "office-support": "Reception area upkeep, pantry restocking, and meeting room preparation.",
  "warehouse-cleaning": "Industrial floor scrub, racking dust-down, and loading bay washdown.",
  "retail-cleaning": "Shop floor mopping, glass front polishing, and fitting room sanitation.",
};

export function getServiceDescription(slug: string): string {
  return SERVICE_DESCRIPTIONS[slug] || "";
}
